image: openjdk:8

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - ./gradlew compileJava
  artifacts:
    paths:
      - jdip_168r1/build
      - tools/conversion/build
    expire_in: 1 day

test:
  stage: test
  script:
    - echo "TBD"

package:
  stage: package
  dependencies:
    - build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - jdip_168r1/build/distributions/*.zip
      - jdip_168r1/build/libs/*.jar
      - tools/conversion/build/distributions/*.jar
      - tools/conversion/build/libs/*.jar
    expire_in: 1 week
