image: openjdk:8

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - ./gradlew compileJava
  artifacts:
    paths:
      - ./**/build
    expire_in: 1 day

test:
  stage: test
  script:
    - echo "TBD"

package:
  stage: package
  dependencies:
    - build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./**/distributions/*.zip
      - ./**/libs/*.jar
    expire_in: 1 week
